api/src/controllers/userControllers.js

Se crearon las rutas getUser y postUser

user controller rutas getUser y postUser

---

client/public/index.html

Se agregó link de la librería Popper para menú desplegable

Link Popper Bootstrap

---

client/src/pages/Admin.js
client/src/pages/Favoritas.js
client/src/pages/MisPreguntas.js
client/src/pages/MisRespuestas.js
client/src/pages/NotFound.js
client/src/pages/Ranking.js
client/src/pages/Responder.js

Se agregó maqueta a páginas:
Admin
NotFound
Ranking
Delete
Mis preguntas 
Mis respuestas
Favoritas

Se agrega maqueta a Admin y resto de páginas

---

client/src/App.js
client/src/components/Butlog.js
client/src/components/Footer.js
client/src/components/Headerlogin.js
client/src/components/styles/Footer.module.css
client/src/components/styles/Headerlogin.module.css
client/src/pages/Terminos.js
client/src/pages/styles/Terminos.module.css

Se agregó página con Términos y condiciones. 
Link en footer para Términos
CSS para textos Header y Footer con links. Agrandar en pantalla menor o igual a 600px

Se agregó página Terminos

---

api/README.API.ENDPOINTS
api/src/controllers/userControllers.js
api/src/controllers/usersControllers.js

se modificaron detalles del readme y se crearon rutas en user y users

se modificaron detalles del readme y se crearon rutas en user y users

---

client/package.json

se agrego mui-icons

---

api/src/controllers/generalControllers.js
client/src/components/CardQuestion.js
client/src/components/CardsQuestions.js
client/src/components/Headerlogin.js
client/src/components/styles/CardQuestion.module.css

La carga de la foto en el headerlogin fue solucionada con modificacion en el useEffect sacando el if state ,..ya que poner [ state ] hace lo mismo.
era como una doble confirmacion de state .... y rompia todo.
Lo otro es una imagen de prueba en card para poder modelar y sumarla a la estructura.
gracias !

Foto solucionado+imagen gonza para user front

---

api/src/controllers/userControllers.js
api/src/routes/userRoutes.js

se creo ruta getUserPoints

---

api/src/controllers/answerControllers.js
api/src/controllers/answersControllers.js
api/src/controllers/generalControllers.js
api/src/controllers/questionControllers.js
api/src/controllers/questionsControllers.js
api/src/controllers/userControllers.js
api/src/controllers/usersControllers.js
api/src/models/User.js

paginate/restriccion of nameChanges/update sort functions/update delete-post cants

paginate/nameChanges/sort functions/delete-post cants

---

client/src/components/CardUserQuestion.js
client/src/components/FilterBar.js
client/src/components/styles/CardUserQuestion.module.css
client/src/components/styles/FilterBar.module.css
client/src/pages/MisPreguntas.js
client/src/pages/styles/MisPreguntas.module.css

Faltan ver algunas funcionalidades

My questions added

---

client/src/components/CardsQuestions.js
client/src/redux/api/index.js

hardcoding en redux / api/ index. js  - linea 19 getallquestions con un " ?page=1&limit=10 " para que no de error el pedido hasta poder hacerlo con el paginado del front.

En cards question/question.result+hardcoding redux api linea 19

---

client/src/components/CardQuestLogOut.js
client/src/components/CardQuestion.js
client/src/pages/Responder.js

Solucionado el grid de principal pero sigue el error de tocar el boton de responder.

Estilo principal recuperado - Sigue error de respuesta

---

client/src/components/CardQuestion.js
client/src/components/Paginated.js
client/src/pages/Favoritas.js

Ver solo lo de useEffect/Link. La parte de favoritos la sigo terminando despues.

Solucionado useEffect/Link

---

client/src/components/CardUserQuestion.js
client/src/pages/Favoritas.js
client/src/pages/styles/Favoritas.module.css

Renderizado sección favoritos.
Faltaría una vez que desde el back nos manden nickname y picture del usuario, descomentar esas líneas.

Pagina favoritos

---

client/src/components/CardUserQuestion.js
client/src/components/FilterBar.js
client/src/components/Paginated.js
client/src/components/SearchBar.js
client/src/components/styles/CardUserQuestion.module.css
client/src/components/styles/FilterBar.module.css
client/src/components/styles/SearchBar.module.css
client/src/pages/MisPreguntas.js
client/src/redux/actions/index.js
client/src/redux/api/index.js

Search myquestions

---

api/index.js
api/src/app.js
api/src/db.js
client/src/index.js
client/src/redux/api/index.js

MODIFIQUE:
En Api:
-index
-app
-db
En Client:
-index (src)
-index (redux)
-index (api)

cambios para poder deployar

---

api/README-API-ENDPOINTS.md
api/src/controllers/answerControllers.js
api/src/controllers/questionControllers.js
api/src/controllers/userControllers.js
api/src/models/Answer.js
api/src/models/Question.js
api/src/models/User.js
client/src/index.js

arreglo typo para deployar

---

api/src/controllers/answersControllers.js
api/src/controllers/generalControllers.js
api/src/controllers/questionControllers.js
api/src/controllers/questionsControllers.js
api/src/controllers/usersControllers.js

filtrado por deleted y banned

---

api/package.json

se agrego nodemon a las dependecias de api

se agrego nodemon a las dependecias de api

---

client/src/pages/styles/Admin.module.css
client/src/pages/styles/Configuracion.module.css
client/src/pages/styles/Favoritas.module.css
client/src/pages/styles/MisPreguntas.module.css
client/src/pages/styles/MisRespuestas.module.css

Más estilos 

---

client/src/index.js

se reemplazo variables del .env

se reemplazo variables del .env

---

client/src/index.js

se cambiaron variables d entorno

se cambiaron variables d entorno

---

client/src/components/Headerlogin.js
client/src/components/Paypal.js
client/src/components/styles/Headerlogin.module.css
client/src/pages/Landing.js
client/src/pages/PaypalPage.js
client/src/pages/styles/Landing.module.css

todo conectado en las estadisticas del landing con refresh funcionando automatico.
Pagina de paypalpage, .y paypal componente creados

Paypal Comp.y page+ mejoras landing

---

client/src/components/Upload.js
client/src/pages/Configuracion.js
client/src/redux/actions/index.js

Quedo solucionado el upload de la foto, agregando un boton para confirmar si el usuario desea subir esa imagen

Solucionado Upload foto

---

client/src/components/FormContact.js
client/src/components/adminComponents/AgregarAdmin.js
client/src/components/adminComponents/Message.js
client/src/components/adminComponents/PreguntasDirectas.js
client/src/components/adminComponents/UserCard.js
client/src/components/adminComponents/styles/Message.module.css
client/src/components/adminComponents/styles/PreguntasDirectas.module.css
client/src/pages/Admin.js
client/src/pages/styles/Admin.module.css
client/src/redux/api/index.js
client/src/redux/reducer/pages.js
client/src/redux/reducer/totalPages.js

Reverts Codebug-Henry/Co-debug#158

Revert "Revert "Preguntas directas funcionando""

---

api/package.json
api/src/controllers/userControllers.js

se incorporo node mailer para post y put user

se incorporo node mailer para post y put user

---

api/src/controllers/messageControllers.js
api/src/controllers/messagesControllers.js
api/src/controllers/userControllers.js
api/src/models/Message.js
api/src/routes/messageRoutes.js

se agregaron rutas y funciones para enviar mail cuando el usuario envia una consulta y cuando el admin responde

se agregaron rutas y funciones para enviar mail

---

api/src/controllers/messageControllers.js
api/src/controllers/userControllers.js

se movieron las variables de nodemailer a .env

se movieron las variables de nodemailer a .env

---

api/src/controllers/alertControllers.js
api/src/controllers/alertsControllers.js
api/src/models/Alert.js
api/src/routes/alertRoutes.js

se modifico alert para poder filtrar por resolved

se modifico alert para poder filtrar por resolved

---

client/src/components/HeaderLoading.js
client/src/components/styles/HeaderLoading.module.css
client/src/components/styles/Headerlogin.module.css
client/src/pages/PagoListo.js
client/src/pages/PaypalPage.js
client/src/pages/styles/Favoritas.module.css
client/src/pages/styles/Landing.module.css
client/src/pages/styles/PagoListo.module.css
client/src/pages/styles/PaypalPage.module.css

-Footer de favoritos abajo
-HeaderLoguin re-size botones
-Alineamiento elementos landing
-Página Pre pago de donación lista.
-Página Post pago de donación lista.
-HeaderLoading adaptado a nuevo formato.

FooterEnFav+HeaderBttns+Landing+PagPagox2+HeaderLoadingNew

---

client/src/components/CardQuestion.js
client/src/components/CardUserQuestion.js
client/src/components/WhatsPop.js
client/src/components/styles/CardQuestion.module.css
client/src/components/styles/WhatsPop.module.css

Link ver Resp+Api sorpresa en mis Preguntas

---

client/src/components/Butlog.js
client/src/components/Header.js

Cada vez que te logueas desde el header, te redirecciona a la pagina en la que estabas

Added returnTo en butlog

---

client/src/components/CardUserQuestion.js
client/src/components/CardsQuestsLogOut.js
client/src/components/Header.js
client/src/components/styles/CardQuestion.module.css
client/src/components/styles/Header.module.css
client/src/components/styles/Headerlogin.module.css
client/src/pages/Ayuda.js
client/src/pages/PagoListo.js
client/src/pages/Ranking.js
client/src/pages/Responder.js
client/src/pages/styles/Ayuda.module.css
client/src/pages/styles/Easter.module.css

x logued out - muestra cuando no encontras preguntas.
x tachito de basura funcionando en Responder
x SACAR VIDEO RECOMENDADO DE YOUTUBE
x INCLUIR VIDEO EN PÁGINA DE AYUDA
x AGREGAR LOGO ANIMADO EN PAGINA LANDING
x REVISAR FILTRO DE DESCARGA DE IMAGEN EN RESPONDER.JS
DE LA PREGUNTA ( FIGURA EXEDENTE DESPUES DEL .JPG )
x sacar la opacidad de el texto en easter egg para   vercel

Cambios varios con davo
